### PR TITLE
store sessions in database

### PR DESCRIPTION
**Pull request by teaforthecat**
I think this might work, but I haven't tried it out yet...

### CODE REVIEW

**Comment by nealmcb** [comment]
Can you expand on what this new DB-Session capability would allow? Is it related to getting a preview of starting an audit?

**Comment by teaforthecat** [comment]
@nealmcb No, it has to do with performance concerns. With this, it would be possible to have more than one web server.

**Comment by teaforthecat** [comment]
This is working pretty smoothly without a measurable performance hit.

**Comment by teaforthecat** [comment]
There is still potential here but it will have to be implemented by someone else.

**Pull request closed without merging**
